/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ClienteDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.ClientePF;
import model.ClientePJ;

/**
 *
 * @author assparremberger
 */
public class ListClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListClientes
     */
    public ListClientes() {
        initComponents();
        carregarTabela();
    }
    
    private void carregarTabela(){
        List<?> lista = new ArrayList<>();
        String[] colunas = {"Código" , "Nome", "Tipo", "CPF / CNPJ", 
            "Cidade", "Email" ,"Aceita Receber Email"};
        if( rbTodos.isSelected() ){
            lista = ClienteDAO.getClientes();
        }else if( rbPF.isSelected() ){
            lista =  ClienteDAO.getClientesPF();
            colunas[3] = "CPF";
        }else {
            lista = ClienteDAO.getClientesPJ();
            colunas[3] = "CNPJ";
        }
        
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers( colunas );
       
        for (Object cliente : lista) {
            Cliente cli = (Cliente) cliente;
            Object[] linha = {};
            String receberEmail = "Não";
            if( cli.isReceberEmail() ){
                receberEmail = "Sim";
            }
            if( cli.getTipo() == Cliente.PESSOA_FISICA ){
                ClientePF pf = (ClientePF) cliente;
                linha = new Object[]{ pf.getId(), pf.getNome(),
                    "Pessoa Física", pf.getCpf(), 
                    pf.getCidade().getNome(), pf.getEmail(), 
                    receberEmail };
            }else{
                ClientePJ pj = (ClientePJ) cliente;
                linha = new Object[]{ pj.getId(), pj.getNome(),
                    "Pessoa Jurídica", pj.getCnpj(), 
                    pj.getCidade().getNome(), pj.getEmail(), 
                    receberEmail };
            }
            model.addRow( linha );
        }
        
        
        tableClientes.setModel( model );
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        rbTodos = new javax.swing.JRadioButton();
        rbPF = new javax.swing.JRadioButton();
        rbPJ = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Clientes");
        setPreferredSize(new java.awt.Dimension(1000, 700));

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Idade"
            }
        ));
        jScrollPane1.setViewportView(tableClientes);

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(rbTodos);
        rbTodos.setSelected(true);
        rbTodos.setText("Todos");
        rbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(rbPF);
        rbPF.setText("Clientes PF");
        rbPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPFActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(rbPJ);
        rbPJ.setText("Clientes PJ");
        rbPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbTodos)
                .addGap(18, 18, 18)
                .addComponent(rbPF)
                .addGap(18, 18, 18)
                .addComponent(rbPJ)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTodos)
                    .addComponent(rbPF)
                    .addComponent(rbPJ))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnExcluir)
                        .addGap(0, 217, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = tableClientes.getSelectedRow();
        if( linha < 0 ){
            JOptionPane.showMessageDialog(this, 
                    "Você deve selecionar um cliente");
        }else{
            String nome = (String) tableClientes.getValueAt(linha, 1);
            int resposta = JOptionPane.showConfirmDialog(this,
                    "Confirma que deseja excluir o cliente " +nome+ "?", 
                    "Excluir Cliente",
                    JOptionPane.YES_NO_OPTION);
            if( resposta == JOptionPane.YES_OPTION){
                int id = (int) tableClientes.getValueAt(linha, 0);
                ClienteDAO.excluir( id );
                carregarTabela();
            }
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void rbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosActionPerformed
        carregarTabela();
    }//GEN-LAST:event_rbTodosActionPerformed

    private void rbPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPFActionPerformed
        carregarTabela();
    }//GEN-LAST:event_rbPFActionPerformed

    private void rbPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPJActionPerformed
        carregarTabela();
    }//GEN-LAST:event_rbPJActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbPF;
    private javax.swing.JRadioButton rbPJ;
    private javax.swing.JRadioButton rbTodos;
    private javax.swing.JTable tableClientes;
    // End of variables declaration//GEN-END:variables
}
